Surround `blacklist` property of java lib in a glob.
Should be 
```
	blacklist = glob([
		'**/*.java',
	]),
```
instead of 
```
	blacklist = [
		'**/*.java',
	],
```

Stacktrace

```
[2016-12-22 14:49:38.656][error][command:null][tid:1020][com.facebook.buck.cli.Main] Uncaught exception at top level
java.util.regex.PatternSyntaxException: Dangling meta character '*' near index 0
**/*.java
^
	at java.util.regex.Pattern.error(Pattern.java:1955)
	at java.util.regex.Pattern.sequence(Pattern.java:2123)
	at java.util.regex.Pattern.expr(Pattern.java:1996)
	at java.util.regex.Pattern.compile(Pattern.java:1696)
	at java.util.regex.Pattern.<init>(Pattern.java:1351)
	at java.util.regex.Pattern.compile(Pattern.java:1028)
	at com.facebook.buck.rules.coercer.PatternTypeCoercer.coerce(PatternTypeCoercer.java:39)
	at com.facebook.buck.rules.coercer.PatternTypeCoercer.coerce(PatternTypeCoercer.java:1)
```